### Logistic Regression

In [4]:
import numpy as np
import matplotlib.pyplot as plt


In [5]:
def sigmoid(x):
    return 1/(1 + np.exp(-1 * x))
def loss_function()

In [8]:
sigmoid()

TypeError: sigmoid() missing 1 required positional argument: 'x'

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A

array([[1, 2],
       [3, 4]])

In [11]:
B

array([[5, 6],
       [7, 8]])

In [13]:
A @ B

array([[19, 22],
       [43, 50]])